version: '3.7'

services:
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - 8080:80
#    volumes:
#      - /Users/bear/projects/auth:/usr/share/nginx/html
#    environment:
#      - NGINX_HOST=localhost
#      - NGINX_PORT=80
#    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bear
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: auth
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:5.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: "80"
    ports:
      - "8181:80"
    links:
      - "db:pgsql-server"

#  auth-back:
#    build: .
#    container_name: auth
#    ports:
#      - "8080:8080"
#    depends_on:
#      - nginx
#      - "db"
#    restart: always